
version: '3'
services: 
    backend:
        build:
            context: .
            dockerfile: DockerFile
        ports: 
            - 80:4000
        restart: on-failure
        env_file:
            - ./.env
        deploy:
            restart_policy:
                condition: on-failure